language: minimal

# Install make
addons:
  apt:
    packages:
      - shellcheck

# Do not build gh-pages
branches:
  except:
  - gh-pages

jobs:
  include:
    - stage: Lint
      addons:
        apt:
          packages:
          - shellcheck
      script:
      - make scripts-lint
    - stage: Lint
      before_script:
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
      script:
      - make chart-lint
    - stage: Deploy
      if: branch = master AND type != pull_request
      services:
        - docker
      before_script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      script:
      - docker build -t gabibbo97/helm-chart-mongodb-assistant:$(cat charts/mongodb/Chart.yaml | cut -d ':' -f 2 | tr -d '\n\t ')
      after_success:
      - docker push gabibbo97/helm-chart-mongodb-assistant:$(cat charts/mongodb/Chart.yaml | cut -d ':' -f 2 | tr -d '\n\t ') gabibbo97/helm-chart-mongodb-assistant:$(cat charts/mongodb/Chart.yaml | cut -d ':' -f 2 | tr -d '\n\t ')
      - docker push gabibbo97/helm-chart-mongodb-assistant:$(cat charts/mongodb/Chart.yaml | cut -d ':' -f 2 | tr -d '\n\t ') gabibbo97/helm-chart-mongodb-assistant:latest
    - stage: Deploy
      if: branch = master AND type != pull_request
      cache:
        directories:
          - repo
      before_script:
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
      script:
      - make chart-package
      deploy:
        local-dir: repo
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
