language: minimal

# Install make
addons:
  apt:
    packages:
      - shellcheck

# Do not build gh-pages
branches:
  except:
  - gh-pages

jobs:
  include:
    - stage: Lint
      addons:
        apt:
          packages:
          - shellcheck
      script:
      - make scripts-lint
    - stage: Lint
      before_script:
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
      script:
      - make chart-lint
    - stage: Functional testing
      language: go
      services:
        - docker
      before_script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
        - go get sigs.k8s.io/kind
        - kind create cluster
        - export KUBECONFIG="$(kind get kubeconfig-path)"
        - kubectl --namespace kube-system create sa tiller
        - kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
        - helm init --wait --service-account tiller
      script:
        - make test
    - stage: deploy
      if: branch = master AND type != pull_request
      cache:
        directories:
          - repo
      before_script:
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
      script:
      - make chart-package
      deploy:
        local-dir: repo
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
