apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        app.kubernetes.io/configuration-checksum: {{ include "dex.config" . | sha256sum | trunc 32 }}
      labels:
        {{- include "dex.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "dex.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/dex
          args:
            - serve
            - /etc/dex/cfg/config.yaml
          ports:
            - name: http
              containerPort: 8080
            - name: telemetry
              containerPort: 8888
          volumeMounts:
            - name: config
              mountPath: /etc/dex/cfg
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: {{ if .Values.dexExternalURL }}{{ trimPrefix "http" .Values.dexExternalURL | trimPrefix "https" | trimPrefix "://" }}{{ else }}{{ (first .Values.ingress.hosts).host }}{{ end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: {{ if .Values.dexExternalURL }}{{ trimPrefix "http" .Values.dexExternalURL | trimPrefix "https" | trimPrefix "://" }}{{ else }}{{ (first .Values.ingress.hosts).host }}{{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
