apiVersion: v1
appVersion: "7.0.0"
description: Keycloak gatekeeper
name: keycloak-gatekeeper
home: https://github.com/keycloak/keycloak-gatekeeper
icon: https://raw.githubusercontent.com/keycloak/keycloak-misc/master/logo/keycloak_logo_600px.png
keywords:
  - authentication
  - authorization
  - keycloak
  - proxy
version: 1.4.0
engine: gotpl
maintainers:
  - name: gabibbo97
    email: gabibbo97@gmail.com
