{{- if eq "script" .Values.tls.ca.managementMode }}
######################
# CA SECRET DELETION #
######################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}-tls-ca-delete-scripts
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeded
data:
  tls.sh: |
{{ .Files.Get "scripts/tls.sh" | indent 4 }}
  uploadca.sh: |
{{ .Files.Get "scripts/uploadca.sh" | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.fullname" . }}-tls-ca-deleter
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mongodb.fullname" . }}-secret-deleter
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeded
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:     ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mongodb.fullname" . }}-tls-ca-deleter
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeded
roleRef:
  apiVersion: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mongodb.fullname" . }}-secret-deleter
subjects:
- kind: ServiceAccount
  name: {{ include "mongodb.fullname" . }}-tls-ca-deleter
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mongodb.fullname" . }}-delete-tls-ca
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tls-ca-deleter
    spec:
      serviceAccountName: {{ include "mongodb.fullname" . }}-tls-ca-deleter
      restartPolicy: Never
      volumes:
      - name: tls-scripts
        configMap:
          defaultMode: 0755
          name: {{ include "mongodb.fullname" . }}-tls-ca-delete-scripts
          optional: false
      containers:
        - name: delete-tls
          image: {{ printf "%s:%s" .Values.images.tls.repository .Values.images.tls.tag }}
          imagePullPolicy: {{ .Values.images.tls.pullPolicy }}
          command: [ '/opt/mongoscripts/uploadca.sh' ]
          args:    [ 'delete' ]
          env:
            - name: SECRET_NAME
              value: {{ include "mongodb.fullname" . }}-tls-ca
          volumeMounts:
            - name: tls-scripts
              mountPath: /opt/mongoscripts
{{- end }}