apiVersion: v1
description: Declarative configuration for imagepullsecrets
name: imagepullsecrets
keywords:
  - authentication
  - secrets
  - docker-registry
  - imagepullsecrets
version: 1.0.0
engine: gotpl
maintainers:
  - name: gabibbo97
    email: gabibbo97@gmail.com
