name: Lint charts

on:
  pull_request:
    paths:
      - charts/**/*
  push:
    paths:
      - charts/**/*
jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Lint using helm
        run: |
          curl -L https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz | tar -xzf - --strip-component=1 linux-amd64/helm
          chmod +x helm
          ./helm lint charts/*
