name: Lint scripts

on:
  pull_request:
    paths:
      - '**/*.sh'
  push:
    paths:
      - '**/*.sh'
jobs:
  scripts-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Lint using shellcheck
        run: |
          apt-get update && apt-get install -y shellcheck
          find . -name '*.sh' -exec shellcheck {} \;
